title: Rafael Rodriguez Sanchez
url: "https://rafarodsa.github.io"
baseurl: "/"
desc: Ph.D. Student in CS at Brown University 
author: Rafael Rodriguez Sanchez

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: UA-175296791-1

footer: yes
footer_url: "https://github.com/rafarodsa"
footer_text: "Page design based on https://ankitsultana.com"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "CV"
   link: "resume.pdf"
# - name: "Contact"
#   link: "contact"
